#!/usr/bin/Rscript 
print ("Section1: Setting the environment") 
rm(list=ls()) 
args <- commandArgs(trailingOnly = TRUE) 
if(length(args) < 2) 
{ 
  stop("Not enough arguments. Please supply 2 arguments.") 
} 
if((args[1]=="-d") == TRUE ) { 
   print ("Parameter check passed") 
}else{ 
   stop ("cannot proceed. Specify the parameters properly. The correct way to use this is predict.r -d data/20140207") 
} 

print ("Section2: Read in the feature files") 
feature1=read.csv(paste(args[2],"fBidP0OfCurrentRow.feature",sep=""), header=FALSE) 
feature2=read.csv(paste(args[2],"fBidP1OfCurrentRow.feature",sep=""), header=FALSE) 
feature3=read.csv(paste(args[2],"fBidP2OfCurrentRow.feature",sep=""), header=FALSE) 
feature4=read.csv(paste(args[2],"fBidP3OfCurrentRow.feature",sep=""), header=FALSE) 
feature5=read.csv(paste(args[2],"fBidP4OfCurrentRow.feature",sep=""), header=FALSE) 
feature6=read.csv(paste(args[2],"fAskP0OfCurrentRow.feature",sep=""), header=FALSE) 
feature7=read.csv(paste(args[2],"fAskP1OfCurrentRow.feature",sep=""), header=FALSE) 
feature8=read.csv(paste(args[2],"fAskP2OfCurrentRow.feature",sep=""), header=FALSE) 
feature9=read.csv(paste(args[2],"fAskP3OfCurrentRow.feature",sep=""), header=FALSE) 
feature10=read.csv(paste(args[2],"fAskP4OfCurrentRow.feature",sep=""), header=FALSE) 
feature11=read.csv(paste(args[2],"fBidQ0OfCurrentRow.feature",sep=""), header=FALSE) 
feature12=read.csv(paste(args[2],"fBidQ1OfCurrentRow.feature",sep=""), header=FALSE) 
feature13=read.csv(paste(args[2],"fBidQ2OfCurrentRow.feature",sep=""), header=FALSE) 
feature14=read.csv(paste(args[2],"fBidQ3OfCurrentRow.feature",sep=""), header=FALSE) 
feature15=read.csv(paste(args[2],"fBidQ4OfCurrentRow.feature",sep=""), header=FALSE) 
feature16=read.csv(paste(args[2],"fAskQ0OfCurrentRow.feature",sep=""), header=FALSE) 
feature17=read.csv(paste(args[2],"fAskQ1OfCurrentRow.feature",sep=""), header=FALSE) 
feature18=read.csv(paste(args[2],"fAskQ2OfCurrentRow.feature",sep=""), header=FALSE) 
feature19=read.csv(paste(args[2],"fAskQ3OfCurrentRow.feature",sep=""), header=FALSE) 
feature20=read.csv(paste(args[2],"fAskQ4OfCurrentRow.feature",sep=""), header=FALSE) 
feature21=read.csv(paste(args[2],"fLTPOfCurrentRow.feature",sep=""), header=FALSE) 

print ("Section3: Read in the prediction model") 
load("e1//design.model")

print ("Section4: Creating the data frame") 
df = data.frame(fBidP0OfCurrentRow=feature1$V2,fBidP1OfCurrentRow=feature2$V2,fBidP2OfCurrentRow=feature3$V2,fBidP3OfCurrentRow=feature4$V2,fBidP4OfCurrentRow=feature5$V2,fAskP0OfCurrentRow=feature6$V2,fAskP1OfCurrentRow=feature7$V2,fAskP2OfCurrentRow=feature8$V2,fAskP3OfCurrentRow=feature9$V2,fAskP4OfCurrentRow=feature10$V2,fBidQ0OfCurrentRow=feature11$V2,fBidQ1OfCurrentRow=feature12$V2,fBidQ2OfCurrentRow=feature13$V2,fBidQ3OfCurrentRow=feature14$V2,fBidQ4OfCurrentRow=feature15$V2,fAskQ0OfCurrentRow=feature16$V2,fAskQ1OfCurrentRow=feature17$V2,fAskQ2OfCurrentRow=feature18$V2,fAskQ3OfCurrentRow=feature19$V2,fAskQ4OfCurrentRow=feature20$V2,fLTPOfCurrentRow=feature21$V2)

print ("Section5: Running logistic regression prediction") 
df$Prob <- predict (logistic.fit, newdata = df, type = "response")


print ("Section6: Creating the time stamps to write in the file") 
dfForFile <- data.frame(df$Prob)
print ("Section7: Putting the timestamps in the data frame as a sanity check mechanism") 
dfForFile <- cbind(dfForFile,feature1) 
dfForFile <- cbind(dfForFile,feature2) 
dfForFile <- cbind(dfForFile,feature3) 
dfForFile <- cbind(dfForFile,feature4) 
dfForFile <- cbind(dfForFile,feature5) 
dfForFile <- cbind(dfForFile,feature6) 
dfForFile <- cbind(dfForFile,feature7) 
dfForFile <- cbind(dfForFile,feature8) 
dfForFile <- cbind(dfForFile,feature9) 
dfForFile <- cbind(dfForFile,feature10) 
dfForFile <- cbind(dfForFile,feature11) 
dfForFile <- cbind(dfForFile,feature12) 
dfForFile <- cbind(dfForFile,feature13) 
dfForFile <- cbind(dfForFile,feature14) 
dfForFile <- cbind(dfForFile,feature15) 
dfForFile <- cbind(dfForFile,feature16) 
dfForFile <- cbind(dfForFile,feature17) 
dfForFile <- cbind(dfForFile,feature18) 
dfForFile <- cbind(dfForFile,feature19) 
dfForFile <- cbind(dfForFile,feature20) 
dfForFile <- cbind(dfForFile,feature21) 

print ("Section8: Saving the predictions in file e1.predictions") 
fileName = paste(args[2],"e1.predictions",sep="") 
print (fileName) 
write.table(dfForFile, file = fileName)